### ISSUE TITLE
Position of loading bar

### ISSUE THREAD

**Issue by IndieWes** [aitboudad/ngx-loading-bar#67]
Any way to position the loading bar inside of a div instead of at the top of the page? I tried in CSS:

```
ngx-loading-bar {
    position: absolute;
}

.parentelement {
    position: relative;
}
```

My template looks like:

```
<div class="parentelement">
    <ngx-loading-bar></ngx-loading-bar>
</div>
```

When I inspect the element in the browser I can see that it does have the correct styling from the stylesheet, but it continues to stay at the top of the page (where it works fine otherwise).

Anything I'm missing? Thanks.

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-sypacw

```scss
.parentelement {
  position: relative;
  ngx-loading-bar {
    display: block;

    #loading-bar-spinner {
      position: absolute;
      top: 5px;
      left: 0px;
    }
    #loading-bar {
      .bar {
        position: absolute;
        .peg {
          display: none;
        }
      }
    } 
  }
}
```

**Comment by IndieWes** [comment]
aitboudad's answer worked for me, thanks a lot.

For those reading this having some issues, I compiled his SCSS into CSS:

`.parentelement {
  position: relative;
}
.parentelement ngx-loading-bar {
  display: block;
}
.parentelement ngx-loading-bar #loading-bar-spinner {
  position: absolute;
  top: 100%;
  left: 1000%;
}
.parentelement ngx-loading-bar #loading-bar .bar {
  position: absolute;
}
.parentelement ngx-loading-bar #loading-bar .bar .peg {
  display: none;
}
`

I don't want the spinner but when I used <ngx-loading-bar [includeSpinner]='false' ></ngx-loading-bar> the loading bar didn't show up. That's why I removed it from the tag and made the 'top' and 'left' properties above big %'s so it doesn't show the spinner on the screen.

**Comment by crabl** [comment]
@aitboudad this solution did not work for me, i'm using `@ngx-loading-bar/core@1.3.1` the position on all elements underneath the `#loading-bar` get set to `fixed`

**Comment by aitboudad** [comment]
@crabl any screenshot ?

**Comment by crabl** [comment]
@aitboudad my mistake! it looks like i tried to add the style in the container component's scss file rather than the global `styles.scss`, it's working as expected now :)

**Comment by aitboudad** [comment]
I was thinking to add an input to specify loading position, any hint about input name and it's possible values ?

**Comment by crabl** [comment]
in my opinion, the two most common scenarios that users of this component are going to run into (which represents about 90% of the use cases) are: either display the bar at the top of the screen (`position: fixed`), or inside a container at a given point on the page (`position: relative` on the container, and `position: absolute` on the bar, as in your example). i'd say a boolean input called `fixed` would be enough to cover these cases. the module i used before for angular 1 didn't even specify that flag, it just allowed the user to apply a container class (see https://www.npmjs.com/package/pg.progress-bars), and didn't set `position: fixed` by default.

**Comment by aitboudad** [comment]
with `1.4.0` you can use `fixed` input instead:
```html
<ngx-loading-bar [fixed]="false"></ngx-loading-bar>
```

**Comment by crabl** [comment]
you rock! 👍

**Comment by 7carlosz** [comment]
[fixed]="false" no work

**Comment by rpvsen** [comment]
@aitboudad, i am trying to change the spinner left to right, its not working. i am using v2.0.0

**Comment by aitboudad** [comment]
@rpvsen RTL direction not supported yet just opened an issue https://github.com/aitboudad/ngx-loading-bar/issues/118 as a feature but this can be done by just overriding the default css:

```css
    ::ng-deep #loading-bar-spinner {
      right: 10px !important;
      left: unset !important;
    }
```
